import "./globals.css";

import { VT323 } from "next/font/google";
import Nav from "@/components/ui/Nav";

const vt323 = VT323({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Nav />
      <body className={`${vt323.className} bg-black px-3 text-white`}>
        {children}
      </body>
    </html>
  );
}
